### ISSUE TITLE
Refactor shortcodes.php

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#116]
This file is getting pretty large and should be refactored to be more object oriented.

This might be something that Nagarjuna can do. @rraub What do you think?

**Comment by chasethenag420** [comment]
pushed changes to branch shortcode-refactor

**Comment by rraub** [comment]
Looks good to me. I might suggest having one file to be the entry point for all the shortcodes and it would just include all the shortcode definition files rather than maintaining a [list of the shortcode files in functions.php](https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/shortcode-refactor/functions.php#L240-L250).

**Comment by idmontie** [comment]
Yeah, I like that idea as well, kind of like how we have our Scss code.

**Comment by rraub** [comment]
Closed in https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/pull/118
