### ISSUE TITLE
Style Footer Collapse Menus

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Wordpress-Theme#175]
![image](https://cloud.githubusercontent.com/assets/412382/10650486/a66b174c-77fe-11e5-91fa-59efdfee6339.png)
https://brandguide.asu.edu/

**Comment by rraub** [comment]
Ours Currently looks like this:  
![screen shot 2016-05-24 at 5 20 01 pm](https://cloud.githubusercontent.com/assets/295804/15524042/c7934578-21d3-11e6-8cb1-cae4ba71367f.png)

We need to:
- [ ] update the arrows so that they point left when they are collapsed an down when the are open.
- [ ] add borders in to match the brandguide site
- [ ] right align the arrows on the row

**Comment by rraub** [comment]
forgot to note that to get the collapsed menus like this the top level items need to be custom links: 
![screen shot 2016-05-31 at 12 05 28 pm](https://cloud.githubusercontent.com/assets/295804/15687168/2c77438c-2728-11e6-8233-43e50e506d6b.png)
