### ISSUE TITLE
Menu wrapping

### ISSUE THREAD

**Issue by bergeson** [gios-asu/ASU-Web-Standards-Wordpress-Theme#218]
When I narrow my browser window, there is a transition time when some of my navigation items move below the menu, and then they are light grey text on white, which is hard to see. Is it possible to have the black background of the menu go with it? Or have it increase in height when the window width forces this?
![screen shot 2016-01-21 at 9 59 45 am](https://cloud.githubusercontent.com/assets/16543935/12486013/4fbdfb10-c026-11e5-9c44-633d34a32934.png)

I little more of a squeeze and it all fixes for a tablet view. Very nice! :)
![screen shot 2016-01-21 at 10 04 38 am](https://cloud.githubusercontent.com/assets/16543935/12486034/6be23d6a-c026-11e5-9ae0-9b5601ad96c1.png)

**Comment by rraub** [comment]
Because the nav is sticky, we dont want it to be more than one line high. Otherwise it will always take up a noticeable part of the page, and drop downs that overlap other drop downs create some weird problems for the user who is mousing over one but not the other.

We do have a setting in the customizer for adjusting the menu padding at the medium width, its under *Menu Styles*, looks like if you tweak it down and remove the duplicate "Home" menu item you should be able to make it all fit.

**Comment by bergeson** [comment]
Excellent suggestion. Thanks! :)
