### ISSUE TITLE
Footer styling is being overridden by new ASU Webstandards Styles

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#274]
We are getting borders on the logo and the contribute button. Also the Contribute button text is being overridden.

![screen shot 2016-06-20 at 3 13 16 pm](https://cloud.githubusercontent.com/assets/295804/16212033/09f86264-36fa-11e6-9b45-c0c4f37b86b0.png)

**Comment by nathan-rollins** [comment]
The css rule '.footer .big-foot a' is overriding the rule '.footer .footer-logo-link' in style.css, causing the underline in the ASU logo.

That same rule (.footer .big-foot a) is also revealing an underline border under the Contribute button, which was invisible due to border color and style (changing maroon solid to grey dotted.) This is overriding .btn-primary.
