### ISSUE TITLE
Disable Google Tag Manager and Lavidge AdWords code when WP is in WP_DEBUG mode

### ISSUE THREAD

**Issue by nathan-rollins** [gios-asu/ASU-Web-Standards-Wordpress-Theme#298]
Just got served a Foresee survey on a local dev site. We should probably disable these trackers when not in production. The easiest solution is probably to wrap them in a conditional block that only runs when WP_DEBUG is false.

**Comment by rraub** [comment]
There is no google analytics tracking in the theme, we have it in our GIOS plugin. I'll repost this issue over there.

**Comment by rraub** [comment]
wow I have a short memory.. https://github.com/gios-asu/ASU-Web-Standards-Wordpress-Theme/blob/develop/analytics-body-tracking-codes.php I stand corrected!

**Comment by rraub** [comment]
Personally, I don't like changing behavior based on a Debug flag. I would expect a debug flag set to true to only print more output for debugging, not enable/disable features. Plus that debug log gets huge really quick, so I only have it on when I need it in development.

That being said there should be a way to turn it off for development/staging. We could add a setting to disable/enable the analytics with it defaulting to on.  Or we use the [Multi-Environment WordPress Configuration examples](https://abandon.ie/notebook/wordpress-configuration-for-multiple-environments) and look for an `ENVIRONMENT` global variable to determine if we're in any mode other than production. If that global is not defined then we will have to assume we're in production so that the analytics work out of the box for everyone.
